version: '3'
services:
  ws:
    build: web_services
    depends_on:
      - db
    ports:
      - "3000:3000"
    network_mode: host
    image: ivanhelmot/brightid-node-web

  anti_sybil:
    build: anti_sybil
    depends_on:
      - ws
      - db
    network_mode: host
    image: ivanhelmot/brightid-node-algorithms

  db:
    build: db_dumps
    network_mode: host
    ports:
      - "8529:8529"
    image: ivanhelmot/brightid-node-db

  web:
    image: nginx
    volumes:
      - ./web_services/brightid-nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    network_mode: host
