version: '3'
services:
  ws:
    build: web_services
    depends_on:
      - db
    network_mode: host
    image: brightid/web_services

  scorer:
    build: scorer
    depends_on:
      - ws
      - db
    network_mode: host
    image: brightid/scorer

  contexts_updater:
    build: contexts_updater
    depends_on:
      - db
    network_mode: host
    image: brightid/contexts_updater

  db:
    build:
      context: ./db
      dockerfile: Dockerfile.with-backup
    network_mode: host
    image: brightid/db

  web:
    image: nginx
    volumes:
      - ./web_services/brightid-nginx.conf:/etc/nginx/nginx.conf
    network_mode: host
