version: "3.2"
services:
  ws:
    build: web_services
    depends_on:
      - db
    image: "ws.brightid.public.dappnode.eth:0.1.0"
    environment:
      BN_WS_IP: db
      BN_WS_PUBLIC_KEY: ""
      BN_WS_PRIVATE_KEY: ""
      BN_WS_ETH_PRIVATE_KEY: ""
  scorer:
    build: scorer
    depends_on:
      - ws
      - db
    image: "scorer.brightid.public.dappnode.eth:0.1.0"
    volumes:
      - "snapshots:/snapshots"
  consensus_receiver:
    build: consensus
    depends_on:
      - ws
      - db
    image: "consensus_receiver.brightid.public.dappnode.eth:0.1.0"
    volumes:
      - "snapshots:/snapshots"
    environment:
      BN_CONSENSUS_INFURA_URL: "wss://idchain.one/ws/"
      BN_CONSENSUS_TO_ADDRESS: "0xb1d1CDd5C4C541f95A73b5748392A6990cBe32b7"
      BN_CONSENSUS_SNAPSHOTS_PERIOD: "240"
      BN_CONSENSUS_APPLY_URL: "http://db:8529/_db/_system/apply{v}/operations/{hash}"
      BN_CONSENSUS_DUMP_URL: "http://db:8529/_api/replication/dump"
      BN_CONSENSUS_MAX_COLLECTION_SIZE: "1000000000"
    entrypoint: python3 -u receiver.py
  consensus_sender:
    build: consensus
    depends_on:
      - ws
      - db
    image: "consensus_sender.brightid.public.dappnode.eth:0.1.0"
    environment:
      BN_CONSENSUS_INFURA_URL: "wss://idchain.one/ws/"
      BN_CONSENSUS_PRIVATE_KEY: ""
      BN_CONSENSUS_GAS: "200000"
      BN_CONSENSUS_GAS_PRICE: "10000000000"
      BN_CONSENSUS_TO_ADDRESS: "0xb1d1CDd5C4C541f95A73b5748392A6990cBe32b7"
    entrypoint: python3 -u sender.py
  updater:
    build: updater
    depends_on:
      - db
    image: "updater.brightid.public.dappnode.eth:0.1.0"
    environment:
      BN_UPDATER_SEED_VOTING_ADDRESS: "0x56741DbC203648983c359A48aaf68f25f5550B6a"
      BN_UPDATER_SP_ADDRESS: "0x0aB346a16ceA1B1363b20430C414eAB7bC179324"
      BN_UPDATER_SP_INFURA_URL: ""
      BN_UPDATER_SEED_GROUPS_WS_URL: "wss://idchain.one/ws/"
  db:
    build: db
    image: "db.brightid.public.dappnode.eth:0.1.0"
    volumes:
      - "data:/var/lib/arangodb3"
      - "apps:/var/lib/arangodb3-apps"
  web:
    build: web
    image: "web.brightid.public.dappnode.eth:0.1.0"
volumes:
  snapshots: {}
  data: {}
  apps: {}
