version: '3.2'
services:
  ws:
    build: web_services
    depends_on:
      - db
    network_mode: host
    image: brightid/web_services
    env_file:
      - config.env

  scorer:
    build: scorer
    depends_on:
      - ws
      - db
    network_mode: host
    image: brightid/scorer
    volumes:
      - type: volume
        source: snapshots
        target: /snapshots
    env_file:
      - config.env

  consensus_receiver:
    build: consensus
    depends_on:
      - ws
      - db
    network_mode: host
    image: brightid/consensus
    volumes:
      - type: volume
        source: snapshots
        target: /snapshots
    env_file:
      - config.env
    entrypoint: python3 -u receiver.py

  consensus_sender:
    build: consensus
    depends_on:
      - ws
      - db
    network_mode: host
    image: brightid/consensus
    env_file:
      - config.env
    entrypoint: python3 -u sender.py

  updater:
    build: updater
    depends_on:
      - db
    network_mode: host
    image: brightid/updater
    env_file:
      - config.env

  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    network_mode: host
    image: brightid/db
    volumes:
      - type: volume
        source: data
        target: /var/lib/arangodb3
      - type: volume
        source: apps
        target: /var/lib/arangodb3-apps
    env_file:
      - config.env
    environment:
      - INIT_BRIGHTID_DB

  web:
    image: nginx
    volumes:
      - ./web_services/brightid-nginx.conf:/etc/nginx/nginx.conf
    network_mode: host
    env_file:
      - config.env

volumes:
  snapshots:
  data:
  apps: